Repository konnn04/rent-house-app, pull requests merged in 2025-06, with the labels that each got.

#23 Bổ sung tính năng
  rent_house/components/auth/AuthStackScreen.js
  rent_house/components/auth/ForgetPassword.js
  rent_house/components/auth/Login.js
  rent_house/components/auth/Register.js
  rent_house/components/main/houses/components/HouseCard.js
  rent_house/components/main/houses/manage/IdentityVerificationScreen.js
  rent_house/components/main/houses/manage/ManageHouse.js
  rent_house/components/main/posts/PostCard.js
  rent_house/contexts/ThemeContext.js
  rent_house/contexts/UserContext.js
  rent_house/locates/vi.json
  rent_house/services/authService.js
  rent_house/services/userService.js
  rent_house_server/api_documentation/authentication_apis.md
  rent_house_server/api_documentation/user_apis.md
  rent_house_server/rent_house/models.py
  rent_house_server/rent_house/serializers/__init__.py
  rent_house_server/rent_house/serializers/auth.py
  rent_house_server/rent_house/serializers/user.py
  rent_house_server/rent_house/services/notification_service.py
  rent_house_server/rent_house/templates/email/reset_password.html
  rent_house_server/rent_house/templates/password_reset/reset_password.html
  rent_house_server/rent_house/urls.py
  rent_house_server/rent_house/views/__init__.py
  rent_house_server/rent_house/views/auth.py
  rent_house_server/rent_house/views/house.py
  rent_house_server/rent_house/views/user.py
Labels: enhancement, feature

#29 Bổ sung sửa trang PostDetail
  rent_house/components/main/posts/CreatePostScreen.js
Labels: bug, feature

#30 Hoàn thiện chức năng xóa nhà của owner
  rent_house/components/main/houses/manage/ManageHouse.jsx
  rent_house/services/houseService.js
Labels: bug, enhancement

#32 Hoàn thiện các chat, tích hợp sẳn firebase
  rent_house/app copy.json
  rent_house/app.json
  rent_house/components/common/Loading.jsx
  rent_house/components/main/Main.jsx
  rent_house/components/main/chat/ChatDetailScreen.jsx
  rent_house/components/main/chat/ChatInfoScreen.jsx
  rent_house/components/main/chat/ChatListScreen.jsx
  rent_house/components/main/chat/CreateGroupChatScreen.jsx
  rent_house/components/main/chat/components/Message.jsx
  rent_house/components/main/chat/components/MessageInput.jsx
  rent_house/components/main/feeds/FeedList.jsx
  rent_house/components/main/houses/detail/HouseDetailScreen.jsx
  rent_house/components/main/houses/detail/RatingsSection.jsx
  rent_house/components/main/houses/manage/AddEditHouseScreen.jsx
  rent_house/components/main/houses/manage/IdentityVerificationScreen.jsx
  rent_house/components/main/houses/manage/ManageHouse.jsx
  rent_house/components/main/houses/rating/AddRatingModal.jsx
  rent_house/components/main/posts/CreatePostScreen.jsx
  rent_house/components/main/posts/PostCard.jsx
  rent_house/components/main/posts/components/CommentItem.jsx
  rent_house/components/main/posts/components/HouseAttachment.jsx
  rent_house/components/main/profiles/PublicProfile.jsx
  rent_house/components/main/profiles/components/ProfileAvatar.jsx
  rent_house/constants/Apis.js
  rent_house/contexts/UserContext.js
  rent_house/firebase.js
  rent_house/package-lock.json
  rent_house/package.json
  rent_house/services/authService.js
  rent_house/services/chatService.js
  rent_house/services/cloudinaryService.js
  rent_house/services/feedService.js
  rent_house/services/firebaseChatService.js
  rent_house/services/houseService.js
  rent_house/services/postService.js
  rent_house/services/profileService.js
  rent_house/services/reportService.js
  rent_house/services/userService.js
  rent_house/styles/style.js
  rent_house/utils/ChatUtils.js
  rent_house_server/rent_house/permissions.py
  rent_house_server/rent_house/urls.py
  rent_house_server/rent_house/views/__init__.py
  rent_house_server/rent_house/views/chat.py
  rent_house_server/rent_house/views/cloudinary_upload.py
  rent_house_server/rent_house/views/comment.py
  rent_house_server/rent_house/views/post.py
  rent_house_server/rent_house_server/settings.py
Labels: bug, documentation, duplicate, enhancement
